trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - script: echo Build your application here
      displayName: 'Build Application'

- stage: Test
  jobs:
  - job: TestJob
    displayName: 'Test Job'
    steps:
    - script: |
        echo Run unit tests here
        echo You can integrate test frameworks like pytest or unittest
      displayName: 'Run Unit Tests'

- stage: Deploy
  jobs:
  - job: DeployJob
    displayName: 'Deployment Job'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    steps:
    - download: none  # Assuming no artifacts are needed, adjust if your build step produces artifacts
    - script: |
        echo Deploying to Azure Web App
        az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
        az webapp up --name <your-webapp-name> --resource-group <your-resource-group> --runtime "PYTHON|3.8"
      displayName: 'Deploy to Azure Web App'
      env:
        servicePrincipalId: $(servicePrincipalId)
        servicePrincipalKey: $(servicePrincipalKey)
        tenantId: $(tenantId)

